---

# apiVersion: networking.gke.io/v1
# kind: ManagedCertificate
# metadata:
#   name: demo
# spec:
#   domains:
#   - test.yourdomain.io
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: demo
spec:
  redirectToHttps:
    enabled: false
---
# apiVersion: networking.k8s.io/v1
# kind: IngressClass
# metadata:
#   name: gce
# spec:
#   controller: "k8s.io/ingress-gce"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: us-west1-docker.pkg.dev/GCP_PROJECT_ID/gcp-devops-repo-01/web-app-test:0.1.0
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "demo-ip"
    networking.gke.io/v1beta1.FrontendConfig: "demo"
    # acme.cert-manager.io/http01-edit-in-place: "true"
    # cert-manager.io/issue-temporary-certificate: "true"
    kubernetes.io/ingress.allow-http: "true"
    # networking.gke.io/managed-certificates: "demo"
spec:
  # ingressClassName: gce
  defaultBackend:
    service:
      name: demo
      port:
        number: 80