name: Deploy Demo Next.js App

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Install the gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: Build and Push the Docker Image
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud auth configure-docker us-west1-docker.pkg.dev 
        docker build -t us-west1-docker.pkg.dev/gcp-devops-project-01/gcp-devops-repo-01/web-app-test:latest .
        docker push us-west1-docker.pkg.dev/gcp-devops-project-01/gcp-devops-repo-01/web-app-test:latest

    - name: Deploy to GKE
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud container clusters get-credentials gke-auto-gcp-devops-project-01-prod --region us-west1
        sed -i "s/GCP_PROJECT_ID/$GCP_PROJECT_ID/g" resources.yaml
        kubectl apply -f resources.yaml
# sed -i "s|<IMAGE_PLACEHOLDER>|us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcp-devops-repo-01/web-app-test:latest|g" resources.yaml